CREATE GLOBAL TEMPORARY TABLE strategy_build
(
	decision_tree_unit_id        NUMBER(38, 0),
	l_exp_slot_id                NUMBER(10, 0),
	l_exp_l_op_bit_string        VARCHAR2(4000),
	l_exp_l_op_bit_string_length NUMBER(10, 0),
	l_exp_l_op_chrom_start_index NUMBER(38, 0),
	l_exp_l_op_id                NUMBER(38, 0),
	l_exp_op_bit_string          VARCHAR2(4000),
	l_exp_op_bit_string_length   NUMBER(10, 0),
	l_exp_op_chrom_start_index   NUMBER(38, 0),
	l_exp_op_id                  NUMBER(38, 0),
	l_exp_r_op_bit_string        VARCHAR2(4000),
	l_exp_r_op_bit_string_length NUMBER(10, 0),
	l_exp_r_op_chrom_start_index NUMBER(38, 0),
	l_exp_r_op_id                NUMBER(38, 0),
	bool_op_bit_string           VARCHAR2(4000),
	bool_op_bit_string_length    NUMBER(10, 0),
	bool_op_chrom_start_index    NUMBER(38, 0),
	bool_op_id                   NUMBER(38, 0),
	r_exp_slot_id                NUMBER(10, 0),
	r_exp_l_op_bit_string        VARCHAR2(4000),
	r_exp_l_op_bit_string_length NUMBER(10, 0),
	r_exp_l_op_chrom_start_index NUMBER(38, 0),
	r_exp_l_op_id                NUMBER(38, 0),
	r_exp_op_bit_string          VARCHAR2(4000),
	r_exp_op_bit_string_length   NUMBER(10, 0),
	r_exp_op_chrom_start_index   NUMBER(38, 0),
	r_exp_op_id                  NUMBER(38, 0),
	r_exp_r_op_bit_string        VARCHAR2(4000),
	r_exp_r_op_bit_string_length NUMBER(10, 0),
	r_exp_r_op_chrom_start_index NUMBER(38, 0),
	r_exp_r_op_id                NUMBER(38, 0),
	l_amt_mult_bit_string        VARCHAR2(4000),
	l_amt_mult_bit_string_length NUMBER(10, 0),
	l_amt_mult_chrom_start_index NUMBER(38, 0),
	l_amt_mult_id                NUMBER(38, 0),
	r_amt_mult_bit_string        VARCHAR2(4000),
	r_amt_mult_bit_string_length NUMBER(10, 0),
	r_amt_mult_chrom_start_index NUMBER(38, 0),
	r_amt_mult_id                NUMBER(38, 0)
) ON COMMIT DELETE ROWS;

ALTER TABLE strategy_build ADD (CONSTRAINT sb_pk_dtuid PRIMARY KEY (decision_tree_unit_id));
