-- connect as SYSTEM.
--SELECT * FROM v$parameter ORDER BY name;
ALTER SYSTEM SET INMEMORY_SIZE = 1G SCOPE = SPFILE;
ALTER SYSTEM SET TEMP_UNDO_ENABLED = TRUE SCOPE = SPFILE;
-- restart db


CREATE TABLESPACE poker_ai_ts DATAFILE 'poker_ai_ts.dbf' SIZE 30G ONLINE DEFAULT INMEMORY;

CREATE USER poker_ai IDENTIFIED BY poker_ai DEFAULT TABLESPACE poker_ai_ts;
GRANT ALL PRIVILEGES TO poker_ai;
GRANT SELECT ANY DICTIONARY to poker_ai;
GRANT AQ_ADMINISTRATOR_ROLE TO poker_ai;
GRANT EXECUTE ON SYS.DBMS_AQ TO poker_ai;
GRANT EXECUTE ON SYS.DBMS_AQADM TO poker_ai;






select * from V$PARAMETER order by name
SELECT * FROM strategy
SELECT * FROM v$sga

SELECT * FROM v$im_segments
SELECT * FROM dba_feature_usage_statistics
ALTER SYSTEM SET TEMP_UNDO_ENABLED = TRUE;