----- drop all
DROP TABLE evolution_trial;
DROP TABLE evolution_trial_work;
DROP TABLE player_state_log;
DROP TABLE poker_ai_log;
DROP TABLE poker_state_log;
DROP TABLE pot_contribution_log;
DROP TABLE pot_log;
DROP TABLE strategy;
DROP TABLE strategy_fitness;
DROP TABLE tournament_result;
DROP SEQUENCE pai_seq_generic;
DROP SEQUENCE pai_seq_sid;
DROP SEQUENCE pai_seq_stratid;
DROP SEQUENCE pai_seq_tid;
BEGIN
	DBMS_AQADM.STOP_QUEUE(queue_name => 'ev_trial_work_queue');
	DBMS_AQADM.DROP_QUEUE(queue_name => 'ev_trial_work_queue');
	DBMS_AQADM.DROP_QUEUE_TABLE(queue_table => 'ev_trial_work_queue_tbl'); 
END;
DROP PACKAGE BODY pkg_ga_evolver;
DROP PACKAGE BODY pkg_poker_ai;
DROP PACKAGE pkg_ga_evolver;
DROP PACKAGE pkg_poker_ai;
DROP TYPE t_tbl_number;
DROP TYPE t_row_evolution_trial_queue;
DROP TYPE t_row_number;
DROP TYPE t_strategy_id_varray;
PURGE RECYCLEBIN;

----- install
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\type\t_strategy_id_varray.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\type\t_row_evolution_trial_queue.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\type\t_row_number.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\type\t_tbl_number.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\sequence\sequences.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\evolution_trial.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\evolution_trial_work.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\player_state_log.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\poker_ai_log.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\poker_state_log.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\pot_contribution_log.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\pot_log.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\strategy.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\strategy_fitness.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\table\tournament_result.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\queue\ev_trial_work_queue.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\package_header\pkg_ga_evolver.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\package_header\pkg_poker_ai.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\package_body\pkg_ga_evolver.sql;
@C:\projects\vs_workspace\poker_ai\poker_ai\db2\package_body\pkg_poker_ai.sql;
